//! 从 `scripts/assets.json`（唯一事实源）派生 sidecar 的受管 env 名册（R11/R12）：
//! `lib.rs` 两处 spawn 共用同一张生成表 —— 「两处各抄一份、各自错」在结构上不可能再发生。
//! 名录缺失 / 不可解析 → 编译失败（fail-closed）。
fn main() {
    gen_asset_env();
    tauri_build::build()
}

fn gen_asset_env() {
    let manifest = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // 仓库根 = CARGO_MANIFEST_DIR/../..（easyvibe-desktop/src-tauri → easyvibe-desktop → root）
    let assets_path = manifest.join("../../scripts/assets.json");
    println!("cargo:rerun-if-changed={}", assets_path.display());
    let raw = std::fs::read_to_string(&assets_path)
        .unwrap_or_else(|e| panic!("读取资产名录失败 {}: {e}", assets_path.display()));
    let assets: serde_json::Value =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("资产名录 JSON 解析失败: {e}"));

    let mut entries = String::new();
    let items = assets
        .get("text_assets")
        .and_then(|v| v.as_array())
        .unwrap_or_else(|| panic!("资产名录缺少 text_assets 数组"));
    for item in items {
        if !item.get("distribute").and_then(|v| v.as_bool()).unwrap_or(true) {
            continue;
        }
        let env = item.get("env").and_then(|v| v.as_str()).unwrap_or("");
        if env.is_empty() {
            continue;
        }
        let name = item.get("name").and_then(|v| v.as_str()).expect("text_asset.name 缺失");
        entries.push_str(&format!("    (\"{env}\", \"{name}\"),\n"));
    }
    let code = format!(
        "// @generated by easyvibe-desktop/src-tauri/build.rs from scripts/assets.json — 请勿手改。\n\
         /// 受管契约文本的 (env 名, 产物文件名) 名册；两处 sidecar spawn 共用同一张表。\n\
         pub const TEXT_ASSET_ENV: &[(&str, &str)] = &[\n{entries}];\n"
    );
    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("asset_env_gen.rs");
    std::fs::write(&out, code).expect("asset_env_gen.rs 写入失败");
}
