//! 编译期派生（本 crate 的 OUT_DIR 生成物）：
//! 1. `embedded_dist.rs` —— 决定内嵌哪个前端产物（既有逻辑，未变）：
//!    - 渲染器 dist 已构建（index.html 存在）→ 内嵌真身（独立分发形态双击 exe 直接出 UI）
//!    - 未构建（只编后端的 CI/交叉编译场景）→ 内嵌占位页，保证编译通过；
//!      EMBEDDED_UI_REAL=false，后端不挂内嵌静态服务（运行时行为与旧版一致：只挂 API）
//! 2. `text_assets_gen.rs` —— 从仓库根 `scripts/assets.json`（唯一事实源）派生受管资产表：
//!    include 常量（MAP_PROMPT 等）+ SPEC 名册。改提示词名 / env 名只改名录，编译期自动跟随；
//!    名录缺失或不可解析 → 编译失败（fail-closed）。
//!
//! 单一事实源是 `easyvibe-renderer/dist` 与 `scripts/assets.json`。
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // ---- ① 前端产物内嵌（既有） ----
    println!("cargo:rerun-if-changed=../../../easyvibe-renderer/dist/index.html");
    let real = manifest.join("../../../easyvibe-renderer/dist/index.html").is_file();
    let dist_code = if real {
        r#"/// 渲染器构建产物内嵌（独立分发形态：后端同源托管 UI）
pub static DIST: ::include_dir::Dir<'static> =
    ::include_dir::include_dir!("$CARGO_MANIFEST_DIR/../../../easyvibe-renderer/dist");
/// 内嵌的是真前端（渲染器已构建）
pub const EMBEDDED_UI_REAL: bool = true;
"#
    } else {
        r#"/// 渲染器未构建——内嵌占位页（只编后端的 CI 场景），运行时不可用
pub static DIST: ::include_dir::Dir<'static> =
    ::include_dir::include_dir!("$CARGO_MANIFEST_DIR/frontend-stub");
/// 内嵌的是占位页（渲染器未构建）
pub const EMBEDDED_UI_REAL: bool = false;
"#
    };
    std::fs::write(out_dir.join("embedded_dist.rs"), dist_code).expect("embedded_dist.rs 写入失败");

    // ---- ② 受管资产名册派生（R12 新增） ----
    // 仓库根 = CARGO_MANIFEST_DIR/../../..（crates/easyvibe-app → crates → easyvibe-backend → root）
    let repo_root = manifest.join("../../..");
    let assets_path = repo_root.join("scripts/assets.json");
    println!("cargo:rerun-if-changed={}", assets_path.display());
    let raw = std::fs::read_to_string(&assets_path)
        .unwrap_or_else(|e| panic!("读取资产名录失败 {}: {e}", assets_path.display()));
    let assets: serde_json::Value =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("资产名录 JSON 解析失败: {e}"));

    let mut consts = String::new();
    let mut specs = String::new();
    let items = assets
        .get("text_assets")
        .and_then(|v| v.as_array())
        .unwrap_or_else(|| panic!("资产名录缺少 text_assets 数组"));
    for item in items {
        let name = item.get("name").and_then(|v| v.as_str()).expect("text_asset.name 缺失");
        let role = item.get("role").and_then(|v| v.as_str()).expect("text_asset.role 缺失");
        let env = item.get("env").and_then(|v| v.as_str()).unwrap_or("");
        let konst = item
            .get("rust_const")
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("text_asset.rust_const 缺失: {name}"));
        let persist = item.get("persist").and_then(|v| v.as_bool()).unwrap_or(false);
        println!("cargo:rerun-if-changed={}", repo_root.join(name).display());
        // include_str! 走 CARGO_MANIFEST_DIR 绝对基准（既有 embedded_dist.rs 已证可行）
        consts.push_str(&format!(
            "pub const {konst}: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../../{name}\"));\n"
        ));
        specs.push_str(&format!(
            "    AssetSpec {{ role: \"{role}\", env: \"{env}\", name: \"{name}\", persist: {persist}, embedded: {konst} }},\n"
        ));
    }
    let code = format!(
        "// @generated by easyvibe-app/build.rs from scripts/assets.json — 请勿手改。\n\
         /// 一份受管契约文本的名册（role/env/name/persist/编译期内嵌内容）。\n\
         #[derive(Clone, Copy, Debug)]\n\
         pub struct AssetSpec {{\n\
         \x20   pub role: &'static str,\n\
         \x20   pub env: &'static str,\n\
         \x20   pub name: &'static str,\n\
         \x20   pub persist: bool,\n\
         \x20   pub embedded: &'static str,\n\
         }}\n\n\
         {consts}\n\
         pub const SPEC: &[AssetSpec] = &[\n{specs}];\n"
    );
    std::fs::write(out_dir.join("text_assets_gen.rs"), code).expect("text_assets_gen.rs 写入失败");
}
